<?php

declare( strict_types=1 );

namespace Fieldify\Fields;

use Blockify\Utilities\Path;
use Blockify\Utilities\Str;
use function add_action;
use function apply_filters;
use function array_replace;
use function dirname;
use function file_exists;
use function filemtime;
use function is_string;
use function register_block_type;
use function str_replace;
use function wp_enqueue_block_style;
use function wp_list_pluck;

/**
 * Blocks.
 *
 * @since 0.1.0
 */
class Blocks {

	public const HOOK = 'fieldify_blocks';

	/**
	 * Project directory.
	 *
	 * @var string
	 */
	private string $project_dir;

	/**
	 * Project URL.
	 *
	 * @var string
	 */
	private string $project_url;

	/**
	 * Package directory.
	 *
	 * @var string
	 */
	private string $package_dir;

	/**
	 * Constructor.
	 *
	 * @param Config $config The package configuration.
	 *
	 * @return void
	 */
	public function __construct( Config $config ) {
		$this->project_dir = Path::get_project_dir( $config->dir );
		$this->project_url = Path::get_project_url( $this->project_dir );
		$this->package_dir = $config->dir;
	}

	/**
	 * Registers a block.
	 *
	 * @param string $id   The block name.
	 * @param array  $args The block arguments.
	 *
	 * @return void
	 */
	public static function register_block( string $id, array $args ): void {
		add_filter(
			static::HOOK,
			static fn( array $blocks ): array => array_merge( $blocks, [ $id => $args ] )
		);
	}

	/**
	 * Register blocks.
	 *
	 * @since 0.1.0
	 *
	 * @hook  init
	 *
	 * @return void
	 */
	public function register_blocks(): void {
		$blocks = $this->get_blocks();

		foreach ( $blocks as $name => $args ) {
			$enabled = $args['enabled'] ?? true;

			if ( ! $enabled ) {
				continue;
			}

			$file = $args['file'] ?? '';

			unset ( $args['file'] );

			if ( $file && file_exists( $file ) ) {

				if ( ! empty( $args ) ) {
					register_block_type( $file, [
						'render_callback' => $args['render_callback'] ?? null,
					] );
				} else {
					register_block_type( $file );
				}
			} else {
				register_block_type( $name, $args );
			}

			$style       = $args['style'] ?? '';
			$project_dir = $this->project_dir;
			$project_url = $this->project_url;

			if ( $style ) {
				$path = $project_dir . $style;

				if ( file_exists( $path ) ) {
					wp_enqueue_block_style(
						$name,
						[
							'handle' => str_replace( '/', '-', $name ),
							'src'    => $project_url . $style,
							'path'   => $path,
							'ver'    => filemtime( $path ),
						]
					);
				}
			}

			$view_script = $args['view_script'] ?? '';

			if ( $view_script && is_string( $view_script ) ) {
				add_action(
					'wp_enqueue_scripts',
					static function () use ( $name, $view_script, $project_dir, $project_url ): void {
						$path = $project_dir . $view_script;
						$src  = $project_url . $view_script;

						if ( ! file_exists( $path ) ) {
							return;
						}

						$base      = basename( $path );
						$dir       = dirname( $path );
						$asset_php = "$dir/asset.php";
						$version   = null;
						$deps      = null;

						if ( file_exists( $asset_php ) ) {
							$asset   = require $asset_php;
							$version = $asset['version'] ?? null;
							$deps    = $asset['dependencies'] ?? null;
						}

						wp_enqueue_script(
							$name,
							$src,
							$deps ?? [],
							$version ?? filemtime( $path ),
							true
						);
					}
				);
			}
		}
	}

	/**
	 * Register the block category.
	 *
	 * @param array $block_categories The block categories.
	 *
	 * @hook block_categories_all 11
	 *
	 * @return array
	 */
	public function register_categories( array $block_categories ): array {
		$blocks = $this->get_blocks();
		$slugs  = wp_list_pluck( $block_categories, 'slug' );

		foreach ( $blocks as $block ) {
			$category = $block['category'] ?? null;

			if ( $category && ! isset( $slugs[ $category ] ) ) {
				$title              = Str::title_case( $category );
				$slugs[ $category ] = $title;

				$block_categories[] = [
					'slug'  => $category,
					'title' => $title,
				];
			}
		}

		return $block_categories;
	}

	/**
	 * Returns array of custom blocks.
	 *
	 * @since 1.0.0
	 *
	 * @return array
	 */
	public function get_blocks(): array {
		$blocks = apply_filters( self::HOOK, [] );

		foreach ( $blocks as $name => $args ) {
			$defaults = [
				'apiVersion' => 2,
				'name'       => $name,
				'title'      => Str::title_case( $name ),
				'category'   => 'custom',
				'attributes' => [],
				'enabled'    => true,
			];

			$blocks[ $name ] = array_replace( $defaults, $args );
		}

		return $blocks;
	}

	/**
	 * Fixes block asset src generated by WP.
	 *
	 * @since 1.0.0
	 *
	 * @param string $src Script or style src.
	 *
	 * @hook  script_loader_src
	 * @hook  style_loader_src
	 *
	 * @return string
	 */
	public function replace_src( string $src ): string {
		$search         = 'plugins' . dirname( __DIR__, 3 );
		$project_parent = Path::get_parts( $this->package_dir, -5 );
		$vendor_dir     = Path::get_parts( $project_parent, 3 );

		if ( Str::contains_all( $src, $search, '/blocks/' ) ) {
			$src = str_replace(
				$search,
				$vendor_dir,
				$src
			);
		}

		return $src;
	}

}
